export const DIRECTIONS = {
    UP: 'up',
    DOWN: 'down',
    LEFT: 'left',
    RIGHT: 'right'
};

export const REVERSE_DIRECTIONS = {};
REVERSE_DIRECTIONS[DIRECTIONS.UP] = DIRECTIONS.DOWN;
REVERSE_DIRECTIONS[DIRECTIONS.DOWN] = DIRECTIONS.UP;
REVERSE_DIRECTIONS[DIRECTIONS.LEFT] = DIRECTIONS.RIGHT;
REVERSE_DIRECTIONS[DIRECTIONS.RIGHT] = DIRECTIONS.LEFT;